
data_path:  /home/aiffel-dj16/dev/KDT_SignLanguageTranslator/SLR-frog/data/sign/27_3/infer_data_joint.npy

# model
model: model.decouple_gcn_attn.Model
model_args:
  num_class: 33
  num_point: 27
  num_person: 1
  graph: graph.sign_27.Graph
  groups: 16
  block_size: 41
  graph_args:
    labeling_mode: 'spatial'

weights: /home/aiffel-dj16/dev/KDT_SignLanguageTranslator/SLR-frog/SL-GCN/final_models/27_3/sign_joint_final2.pt 

label : 
  0 : 제가 많이 급합니다.
  1 : 1호선을 타는 곳은 어디인가요?
  2 : 있습니다
  3 : 출구가 어디에 있나요?
  4 : 다음 역까지 몇 분 걸리나요?
  5 : 도착하려면 몇 분 남았을까요?
  6 : 반대편 승차장으로 어떻게 갈 수 있나요?
  7 : 이름이 어떻게 되세요?
  8 : 민원은 어디에 넣나요?
  9 : 몇 분 지연되었나요?
  10 : 몇 번에서 타면 되나요?
  11 : 안녕하세요.
  12 : 감사합니다.
  13 : 타는 곳이 맞나요?
  14 : 여기서 내리는 것이 맞나요?
  15 : 지갑을 잃어버렸습니다.
  16 : 트렁크 좀 열어주세요.
  17 : 안내소는 어디에 있나요?
  18 : 계단은 어디에 있나요?
  19 : 카드 인식이 안되네요.
  20 : 서울대학교 방향으로 가려면 어떻게 가나요?
  21 : 맞습니다.
  22 : 알겠습니다.
  23 : 필요없습니다.
  24 : 우산을 분실하였습니다.
  25 : 불편합니다.
  26 : 다와가나요?
  27 : 기차역
  28 : 휴학
  29 : 나
  30 : 친하다
  31 : 사람
  32 : 명동
